# Generated by Django 3.1.2 on 2021-03-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('rg', models.CharField(max_length=9)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('data_nascimento', models.DateField()),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('celular', models.CharField(max_length=14)),
                ('foto', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
